# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoiBye2017', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='type_of_article',
            field=models.CharField(blank='Feminism', max_length=100),
        ),
    ]
