# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BoiBye2017', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BoiBye2017.Articles'),
        ),
    ]
